name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install vsce
        run: npm install -g vsce

      - name: Install dependencies
        run: npm install

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: "version" # optional: you can specify a prefix for your tag here
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PACKAGEJSON_DIR: "." # specify the location of your package.json if it's not in the root

      - name: Package Extension
        run: vsce package

      - name: Publish Extension
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
