name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Start Xvfb
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xvfb
          Xvfb :99 &
        env:
          DISPLAY: ":99"
        if: runner.os == 'Linux'

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm run test
        env:
          DISPLAY: ":99"

      - name: Configure Git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Bump version
        run: npm version patch

      - name: Push changes
        run: git push

      - name: Publish via vsce
        run: npm run deploy
