name: CI/CD Pipeline for main

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch
    tags:
      - "*" # Also runs the workflow when you push a tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests on Linux
        run: xvfb-run -a npm run test
        if: runner.os == 'Linux'

      - name: Run Tests on macOS and Windows
        run: npm run test
        if: runner.os != 'Linux'

      # Conditional Publish
      - name: Publish
        if: success()
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
