name: CI/CD Pipeline for main

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests on Linux
        run: xvfb-run -a npm run test
        if: runner.os == 'Linux'

      - name: Run Tests on macOS and Windows
        run: npm run test
        if: runner.os != 'Linux'

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Publish
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
